export const homeObjOne = {
    id:'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Game Night',
    headline: 'Finding the right game for you and the family.',
    description: 'Answer a few questions and be able to find games that you can play with your friends and family. It only takes a few quick moments!',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../assets/game4.svg').default,
    alt:'Dice',
    dark:true,
    primary:true,
    darkText:false,
};

export const homeObjTwo = {
    id:'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'So much gaming for you!',
    headline: 'Finding the right game for you and the family.',
    description: 'Answer a few questions and be able to find games that you can play with your friends and family. It only takes a few quick moments!',
    buttonLabel: 'Learn - more!',
    imgStart: true,
    img: require('../../assets/game1.svg').default,
    alt:'gamestuff',
    dark:false,
    primary:false,
    darkText:true,
};

export const homeObjThree = {
    id:'services1',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Get access to as many games as you would like!',
    headline: 'Finding the right game for you and the family.',
    description: 'This is easy! Make the jump today to find out the best gaming options available to you!',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../assets/game2.svg').default,
    alt:'Dice',
    dark: true,
    primary:true,
    darkText:false,
};